### ISSUE TITLE
环境异常 当前环境异常，完成验证后即可继续访问。  去验证

### ISSUE THREAD

**Issue by yangql0532** [ahxiaoqi/wechatDownload#1]
你好，批量下载的时候报错
返回报这个问题：
环境异常
当前环境异常，完成验证后即可继续访问。

去验证
是因为代理设置的不对吗？

**Comment by ahxiaoqi** [comment]
应该是太频繁了吧,我也只是临时加了一点百度翻译的功能.大概率是触发官方反爬了

**Comment by ahxiaoqi** [comment]
因为原作者停止维护,我非fork直接传上来也就算留个档,原始仓库地址README里写了.是这个地址  https://github.com/xiaoguyu/wechatDownload

**Comment by yangql0532** [comment]
嗯，谢谢，就是上来问问，你的正常吗

**Comment by ahxiaoqi** [comment]
我还没有批量下过,就零星的几篇搞了个翻译
